#!/usr/bin/env node

/**
 * Environment Setup Script
 * Creates .env.local file for local development
 */

const fs = require('fs');
const path = require('path');

const envContent = `# Local Development Environment Variables
# Generated by setup-env.js

# Supabase Configuration
VITE_REACT_APP_SUPABASE_URL=your-supabase-url-here
VITE_REACT_APP_SUPABASE_ANON_KEY=your-supabase-anon-key-here

# Authentication Credentials (CHANGE THESE!)
VITE_REACT_APP_OWNER_USERNAME=your-secure-username
VITE_REACT_APP_OWNER_PASSWORD=your-secure-password
VITE_REACT_APP_STAFF_USERNAME=your-staff-username
VITE_REACT_APP_STAFF_PASSWORD=your-staff-password

# Settings PIN (CHANGE THIS!)
VITE_REACT_APP_DEFAULT_PIN=your-secure-pin

# Session Configuration
VITE_REACT_APP_SESSION_TIMEOUT=1800000
VITE_REACT_APP_MAX_LOGIN_ATTEMPTS=3
VITE_REACT_APP_LOCKOUT_DURATION=300000

# App Configuration
VITE_REACT_APP_APP_NAME=Milk Delivery App
VITE_REACT_APP_VERSION=1.0.0
VITE_REACT_APP_ENVIRONMENT=development
`;

const envPath = path.join(__dirname, 'frontend', '.env.local');

try {
  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    console.log('⚠️  .env.local already exists!');
    console.log('   If you want to regenerate it, delete the existing file first.');
    process.exit(0);
  }

  // Create the .env.local file
  fs.writeFileSync(envPath, envContent);
  
  console.log('✅ Environment file created successfully!');
  console.log('📁 Location: frontend/.env.local');
  console.log('');
  console.log('🔐 IMPORTANT SECURITY NOTES:');
  console.log('   • Change default credentials before production');
  console.log('   • Update PIN from 6969 to a secure value');
  console.log('   • Never commit .env.local to version control');
  console.log('');
  console.log('🚀 Next steps:');
  console.log('   1. Review and update credentials in frontend/.env.local');
  console.log('   2. Run: cd frontend && npm run dev');
  console.log('   3. Test the application locally');
  
} catch (error) {
  console.error('❌ Error creating environment file:', error.message);
  process.exit(1);
}
